import numpy as np

terranUnits = [
    ("TERRAN_TECHLAB", False, [5]),
    ("TERRAN_REACTOR", False, [6]),
    # ("TERRAN_POINTDEFENSEDRONE", False, [11]),
    ("TERRAN_COMMANDCENTER", False, [18, 36]),
    ("TERRAN_SUPPLYDEPOT", False, [19, 47]),
    ("TERRAN_REFINERY", False, [20]),
    ("TERRAN_BARRACKS", False, [21, 46]),
    ("TERRAN_ENGINEERINGBAY", False, [22]),
    ("TERRAN_MISSILETURRET", False, [23]),
    ("TERRAN_BUNKER", False, [24]),
    ("TERRAN_SENSORTOWER", False, [25]),
    ("TERRAN_GHOSTACADEMY", False, [26]),
    ("TERRAN_FACTORY", False, [27, 43]),
    ("TERRAN_STARPORT", False, [28, 44]),
    ("TERRAN_ARMORY", False, [29]),
    ("TERRAN_FUSIONCORE", False, [30]),
    ("TERRAN_AUTOTURRET", False, [31]),
    ("TERRAN_SIEGETANK", True, [33, 32]),
    ("TERRAN_VIKINGFIGHTER", True, [35, 34]),
    ("TERRAN_BARRACKSTECHLAB", False, [37]),
    ("TERRAN_BARRACKSREACTOR", False, [38]),
    ("TERRAN_FACTORYTECHLAB", False, [39]),
    ("TERRAN_FACTORYREACTOR", False, [40]),
    ("TERRAN_STARPORTTECHLAB", False, [41]),
    ("TERRAN_STARPORTREACTOR", False, [42]),
    ("TERRAN_SCV", False, [45]),
    ("TERRAN_MARINE", True, [48]),
    ("TERRAN_REAPER", True, [49]),
    ("TERRAN_GHOST", True, [50]),
    ("TERRAN_MARAUDER", True, [51]),
    ("TERRAN_THOR", True, [52, 691]),
    ("TERRAN_HELLION", True, [53]),
    ("TERRAN_MEDIVAC", True, [54]),
    ("TERRAN_BANSHEE", True, [55]),
    ("TERRAN_RAVEN", True, [56]),
    ("TERRAN_BATTLECRUISER", True, [57]),
    ("TERRAN_NUKE", False, [58]),
    ("TERRAN_PLANETARYFORTRESS", False, [130]),
    ("TERRAN_ORBITALCOMMAND", False, [132, 134]),
    ("TERRAN_MULE", False, [268]),
    ("TERRAN_HELLIONTANK", True, [484]),
    ("TERRAN_WIDOWMINE", True, [498, 500]),
    ("TERRAN_LIBERATOR", True, [689, 734]),
    ("TERRAN_CYCLONE", True, [692]),
    # ("TERRAN_KD8CHARGE", False, [830]),
]

zergUnits = [
    ("ZERG_INFESTORTERRAN", True, [7]),
    ("ZERG_BANELINGCOCOON", True, [8]),
    ("ZERG_BANELING", True, [9, 115]),
    ("ZERG_CHANGELING", True, [12, 13, 14, 15, 16, 17]),
    ("ZERG_HATCHERY", False, [86]),
    ("ZERG_CREEPTUMOR", False, [87, 137, 138]),
    ("ZERG_EXTRACTOR", False, [88]),
    ("ZERG_SPAWNINGPOOL", False, [89]),
    ("ZERG_EVOLUTIONCHAMBER", False, [90]),
    ("ZERG_HYDRALISKDEN", False, [91]),
    ("ZERG_SPIRE", False, [92]),
    ("ZERG_ULTRALISKCAVERN", False, [93]),
    ("ZERG_INFESTATIONPIT", False, [94]),
    ("ZERG_NYDUSNETWORK", False, [95]),
    ("ZERG_BANELINGNEST", False, [96]),
    ("ZERG_ROACHWARREN", False, [97]),
    ("ZERG_SPINECRAWLER", False, [98, 139]),
    ("ZERG_SPORECRAWLER", False, [99, 140]),
    ("ZERG_LAIR", False, [100]),
    ("ZERG_HIVE", False, [101]),
    ("ZERG_GREATERSPIRE", False, [102]),
    ("ZERG_EGG", False, [103]),
    ("ZERG_DRONE", False, [104, 116]),
    ("ZERG_ZERGLING", True, [105, 119]),
    ("ZERG_OVERLORD", False, [106]),
    ("ZERG_HYDRALISK", True, [107, 117]),
    ("ZERG_MUTALISK", True, [108]),
    ("ZERG_ULTRALISK", True, [109]),
    ("ZERG_ROACH", True, [110, 118]),
    ("ZERG_INFESTOR", True, [111, 127]),
    ("ZERG_CORRUPTOR", True, [112]),
    ("ZERG_BROODLORDCOCOON", True, [113]),
    ("ZERG_BROODLORD", True, [114]),
    ("ZERG_QUEEN", False, [126, 125]),
    ("ZERG_OVERLORDCOCOON", True, [128]),
    ("ZERG_OVERSEER", True, [129]),
    ("ZERG_NYDUSCANAL", False, [142]),
    ("ZERG_INFESTEDTERRANSEGG", True, [150]),
    ("ZERG_LARVA", False, [151]),
    ("ZERG_BROODLING", True, [289]),
    ("ZERG_LOCUSTMP", True, [489, 693]),
    ("ZERG_SWARMHOSTMP", True, [494, 493]),
    ("ZERG_VIPER", True, [499]),
    ("ZERG_LURKERMPEGG", True, [501]),
    ("ZERG_LURKERMP", True, [502, 503]),
    ("ZERG_LURKERDENMP", False, [504]),
    ("ZERG_RAVAGERCOCOON", True, [687]),
    ("ZERG_RAVAGER", True, [688]),
    # ("ZERG_PARASITICBOMBDUMMY", True, [824]),
    ("ZERG_TRANSPORTOVERLORDCOCOON", True, [892]),
    ("ZERG_OVERLORDTRANSPORT", True, [893]),
]

protossUnits = [
    ("PROTOSS_COLOSSUS", True, [4]),
    ("PROTOSS_MOTHERSHIP", True, [10]),
    ("PROTOSS_NEXUS", False, [59]),
    ("PROTOSS_PYLON", False, [60, 894]),
    ("PROTOSS_ASSIMILATOR", False, [61]),
    ("PROTOSS_GATEWAY", False, [62]),
    ("PROTOSS_FORGE", False, [63]),
    ("PROTOSS_FLEETBEACON", False, [64]),
    ("PROTOSS_TWILIGHTCOUNCIL", False, [65]),
    ("PROTOSS_PHOTONCANNON", False, [66]),
    ("PROTOSS_STARGATE", False, [67]),
    ("PROTOSS_TEMPLARARCHIVE", False, [68]),
    ("PROTOSS_DARKSHRINE", False, [69]),
    ("PROTOSS_ROBOTICSBAY", False, [70]),
    ("PROTOSS_ROBOTICSFACILITY", False, [71]),
    ("PROTOSS_CYBERNETICSCORE", False, [72]),
    ("PROTOSS_ZEALOT", True, [73]),
    ("PROTOSS_STALKER", True, [74]),
    ("PROTOSS_HIGHTEMPLAR", True, [75]),
    ("PROTOSS_DARKTEMPLAR", True, [76]),
    ("PROTOSS_SENTRY", True, [77]),
    ("PROTOSS_PHOENIX", True, [78]),
    ("PROTOSS_CARRIER", True, [79]),
    ("PROTOSS_VOIDRAY", True, [80]),
    ("PROTOSS_WARPPRISM", True, [81, 136]),
    ("PROTOSS_OBSERVER", True, [82]),
    ("PROTOSS_IMMORTAL", True, [83]),
    ("PROTOSS_PROBE", False, [84]),
    ("PROTOSS_INTERCEPTOR", True, [85]),
    ("PROTOSS_WARPGATE", False, [133]),
    ("NEUTRAL_FORCEFIELD", True, [135]),
    ("PROTOSS_ARCHON", True, [141]),
    ("PROTOSS_ADEPT", True, [311, 801]),
    ("PROTOSS_MOTHERSHIPCORE", True, [488]),
    ("PROTOSS_ORACLE", True, [495]),
    ("PROTOSS_TEMPEST", True, [496]),
    ("PROTOSS_DISRUPTOR", True, [694]),
    ("PROTOSS_ORACLESTASISTRAP", False, [732]),
    ("PROTOSS_DISRUPTORPHASED", True, [733]),
    ("PROTOSS_SHIELDBATTERY", False, [1910]),
]

ignoredUnits = {
    1942,  # ParasiticBombRelayDummy
    830,  # TERRAN_KD8CHARGE
    824,  # ZERG_PARASITICBOMBDUMMY
    11,  # TERRAN_POINTDEFENSEDRONE
}

upgrades = [
    # ("INVALID", 0),
    ("CARRIERLAUNCHSPEEDUPGRADE", 1),
    ("GLIALRECONSTITUTION", 2),
    ("TUNNELINGCLAWS", 3),
    ("CHITINOUSPLATING", 4),
    ("HISECAUTOTRACKING", 5),
    ("TERRANBUILDINGARMOR", 6),
    ("TERRANINFANTRYWEAPONSLEVEL1", 7),
    ("TERRANINFANTRYWEAPONSLEVEL2", 8),
    ("TERRANINFANTRYWEAPONSLEVEL3", 9),
    ("NEOSTEELFRAME", 10),
    ("TERRANINFANTRYARMORSLEVEL1", 11),
    ("TERRANINFANTRYARMORSLEVEL2", 12),
    ("TERRANINFANTRYARMORSLEVEL3", 13),
    ("STIMPACK", 15),
    ("SHIELDWALL", 16),
    ("PUNISHERGRENADES", 17),
    ("HIGHCAPACITYBARRELS", 19),
    ("BANSHEECLOAK", 20),
    ("RAVENCORVIDREACTOR", 22),
    ("PERSONALCLOAKING", 25),
    ("TERRANVEHICLEWEAPONSLEVEL1", 30),
    ("TERRANVEHICLEWEAPONSLEVEL2", 31),
    ("TERRANVEHICLEWEAPONSLEVEL3", 32),
    ("TERRANSHIPWEAPONSLEVEL1", 36),
    ("TERRANSHIPWEAPONSLEVEL2", 37),
    ("TERRANSHIPWEAPONSLEVEL3", 38),
    ("PROTOSSGROUNDWEAPONSLEVEL1", 39),
    ("PROTOSSGROUNDWEAPONSLEVEL2", 40),
    ("PROTOSSGROUNDWEAPONSLEVEL3", 41),
    ("PROTOSSGROUNDARMORSLEVEL1", 42),
    ("PROTOSSGROUNDARMORSLEVEL2", 43),
    ("PROTOSSGROUNDARMORSLEVEL3", 44),
    ("PROTOSSSHIELDSLEVEL1", 45),
    ("PROTOSSSHIELDSLEVEL2", 46),
    ("PROTOSSSHIELDSLEVEL3", 47),
    ("OBSERVERGRAVITICBOOSTER", 48),
    ("GRAVITICDRIVE", 49),
    ("EXTENDEDTHERMALLANCE", 50),
    ("PSISTORMTECH", 52),
    ("ZERGMELEEWEAPONSLEVEL1", 53),
    ("ZERGMELEEWEAPONSLEVEL2", 54),
    ("ZERGMELEEWEAPONSLEVEL3", 55),
    ("ZERGGROUNDARMORSLEVEL1", 56),
    ("ZERGGROUNDARMORSLEVEL2", 57),
    ("ZERGGROUNDARMORSLEVEL3", 58),
    ("ZERGMISSILEWEAPONSLEVEL1", 59),
    ("ZERGMISSILEWEAPONSLEVEL2", 60),
    ("ZERGMISSILEWEAPONSLEVEL3", 61),
    ("OVERLORDSPEED", 62),
    ("BURROW", 64),
    ("ZERGLINGATTACKSPEED", 65),
    ("ZERGLINGMOVEMENTSPEED", 66),
    ("ZERGFLYERWEAPONSLEVEL1", 68),
    ("ZERGFLYERWEAPONSLEVEL2", 69),
    ("ZERGFLYERWEAPONSLEVEL3", 70),
    ("ZERGFLYERARMORSLEVEL1", 71),
    ("ZERGFLYERARMORSLEVEL2", 72),
    ("ZERGFLYERARMORSLEVEL3", 73),
    ("INFESTORENERGYUPGRADE", 74),
    ("CENTRIFICALHOOKS", 75),
    ("BATTLECRUISERENABLESPECIALIZATIONS", 76),
    ("PROTOSSAIRWEAPONSLEVEL1", 78),
    ("PROTOSSAIRWEAPONSLEVEL2", 79),
    ("PROTOSSAIRWEAPONSLEVEL3", 80),
    ("PROTOSSAIRARMORSLEVEL1", 81),
    ("PROTOSSAIRARMORSLEVEL2", 82),
    ("PROTOSSAIRARMORSLEVEL3", 83),
    ("WARPGATERESEARCH", 84),
    ("CHARGE", 86),
    ("BLINKTECH", 87),
    ("PHOENIXRANGEUPGRADE", 99),
    ("NEURALPARASITE", 101),
    ("TERRANVEHICLEANDSHIPARMORSLEVEL1", 116),
    ("TERRANVEHICLEANDSHIPARMORSLEVEL2", 117),
    ("TERRANVEHICLEANDSHIPARMORSLEVEL3", 118),
    ("DRILLCLAWS", 122),
    ("ADEPTPIERCINGATTACK", 130),
    ("MAGFIELDLAUNCHERS", 133),
    ("EVOLVEGROOVEDSPINES", 134),
    ("EVOLVEMUSCULARAUGMENTS", 135),
    ("BANSHEESPEED", 136),
    ("RAVENRECALIBRATEDEXPLOSIVES", 138),
    ("MEDIVACINCREASESPEEDBOOST", 139),
    ("LIBERATORAGRANGEUPGRADE", 140),
    ("DARKTEMPLARBLINKUPGRADE", 141),
    ("SMARTSERVOS", 289),
    ("RAPIDFIRELAUNCHERS", 291),
    ("ENHANCEDMUNITIONS", 292),
]


class UnitLookup:
   def __init__(self, units):
      self.units = units
      self.num_units = len(units)
      self.military_units_mask = np.zeros(self.num_units)
      self.all_unit_indices = list(range(0, self.num_units))
      self.unit_index_map = {}
      self.reverse_unit_index_map = {}
      self.upgrade_index_map = {}
      self.num_upgrades = len(upgrades)
      for i, u in enumerate(upgrades):
        self.upgrade_index_map[u[1]] = i

      for i, unit in enumerate(units):
         self.military_units_mask[i] = 1 if unit[1] else 0
         self.reverse_unit_index_map[i] = unit[2][0]
         for index in unit[2]:
            self.unit_index_map[index] = i

      self.military_units_mask_indices = np.where(self.military_units_mask)[0]
      self.non_military_units_mask_indices = np.where(self.military_units_mask == False)[0]
